_target_: src.models.intel_module.LitResnet

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  #lr: 0.001
  lr: 0.0476321232531695
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: timm.create_model
  model_name: resnet18
  pretrained: True
  num_classes: 6
  
